<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Interfaces\IWeatherService.cs~RF2e996d1b.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Technical_Test.Domain\Technical_Test.Domain.csproj" />
  </ItemGroup>

</Project>
